name: Build Kernel

on: 
  push:
    branches: main

env:
  KERNEL: https://github.com/HydrogenKernel/Hydrogen
  KERNEL_BRANCH: S4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup Envoirment
         run: |
            sudo -E apt-get -qq install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison    

       - name: Clone Kernel and Proton Clang
         run: |
            git clone $KERNEL --depth=1 -b $KERNEL_BRANCH kernel
            git clone -q --depth=1 --single-branch https://github.com/kdrag0n/proton-clang tc/proton-clang
            
       - name: Building
         run: |
            cd kernel
            bash build.sh
            
       - uses: actions/upload-artifact@v2
         with:
          name: HydrogenKernel
          path: kernel/*.zip
